using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using MinimalEndpoints.CodeGeneration.Endpoints.Models;
using MinimalEndpoints.CodeGeneration.Groups;
using MinimalEndpoints.CodeGeneration.Groups.Models;
using MinimalEndpoints.CodeGeneration.Models;
using MinimalEndpoints.CodeGeneration.Utilities;

namespace MinimalEndpoints.CodeGeneration;

internal static class MinimalEndpointsFileBuilder
{
    public static CSharpFileScope GenerateFile(
        string namespaceName,
        string className,
        List<EndpointDefinition> endpoints,
        GroupHierarchy hierarchy
    )
    {
        if (!endpoints.Any() && hierarchy.Count == 0)
        {
            return null;
        }

        var fileScope = CreateFileScope(namespaceName, className);

        // Resolve method/variable names up front, disambiguating any sanitized-name collisions so
        // the declaration and every call site use the same (unique) identifier.
        var names = GeneratedNames.Build(endpoints, hierarchy.Groups);

        fileScope.AddMinimalEndpointsRegistrationMethod(endpoints, [..hierarchy.Groups]);

        // Add group mapping methods
        foreach (var group in hierarchy.Groups)
        {
            fileScope.AddGroupMapMethod(group, hierarchy, names);
        }

        foreach (var endpoint in endpoints)
        {
            fileScope.AddMinimalEndpointMapMethod(endpoint, hierarchy, names);
        }

        fileScope.AddMinimalEndpointsMapAllMethods(endpoints, hierarchy, names);

        return fileScope;
    }

    public static CSharpFileScope CreateFileScope(string namespaceName, string className)
    {
        // The generated extension class is internal: AddMinimalEndpoints()/UseMinimalEndpoints() are
        // always called from the same assembly the generator ran in, and a fixed public type in a
        // fixed namespace collides (CS0436) when two referencing projects both run the generator.
        return new CSharpFileScope("internal static", namespaceName, className)
            .WithHeader("""
                        //----------------------
                        // <auto-generated>
                        //     This file was generated by MinimalEndpoints.CodeGeneration.EndpointGenerator.
                        //     Do not edit this file manually.
                        // </auto-generated>
                        //----------------------
                        #nullable enable
                        """
            )
            .AddUsing("System")
            .AddUsing("System.Threading")
            .AddUsing("System.Threading.Tasks")
            .AddUsing("System.Collections.Generic")
            .AddUsing("System.CodeDom.Compiler")
            .AddUsing("Microsoft.AspNetCore.Builder")
            .AddUsing("Microsoft.AspNetCore.Routing")
            .AddUsing("Microsoft.AspNetCore.Http")
            .AddUsing("Microsoft.Extensions.DependencyInjection")
            .AddUsing("Microsoft.AspNetCore.Mvc")
            .AddUsing("MinimalEndpoints")
            .AddClassAttribute("[GeneratedCode(\"MinimalEndpoints.CodeGeneration.EndpointGenerator\", \"1.0.0\")]");
    }

    private static CSharpFileScope AddMinimalEndpointsRegistrationMethod(
        this CSharpFileScope fileScope,
        List<EndpointDefinition> endpoints,
        ImmutableArray<EndpointGroupDefinition> groupDefinitions
    )
    {
        if (endpoints.Count == 0 && groupDefinitions.Length == 0)
        {
            return fileScope;
        }

        var method = fileScope.AddMethod(
            modifiers: "public static",
            returnType: "IServiceCollection",
            methodName: "AddMinimalEndpoints",
            parameters: "this IServiceCollection services"
        );

        var usings = fileScope.GetAvailableUsings();

        // Groups are no longer registered in DI: ConfigureGroup is a static abstract member,
        // invoked statically during mapping, so no group instance is ever resolved.

        // Register endpoints
        foreach (var endpoint in endpoints)
        {
            var lifetime = GetLifetimeMethodName(endpoint.MapMethodsAttribute.Lifetime);
            var classTypeName = endpoint.ClassType.ToDisplayString(usings);

            var registrationLine = endpoint.MapMethodsAttribute.ServiceName != null
                ? $"services.{lifetime}<{endpoint.MapMethodsAttribute.ServiceName}, {classTypeName}>();"
                : $"services.{lifetime}<{classTypeName}>();";

            method.AddLine(registrationLine);
        }

        method.AddLine("return services;");

        return fileScope;
    }

    private static CSharpFileScope AddGroupMapMethod(this CSharpFileScope fileScope,
        EndpointGroupDefinition groupDefinition, GroupHierarchy hierarchy, GeneratedNames names)
    {
        var usings = fileScope.GetAvailableUsings();

        var hasParent = hierarchy.Parent(groupDefinition) != null;

        // Determine parameters: if it has parent, need parent group parameter
        var parameters = hasParent
            ? "this IEndpointRouteBuilder builder, IApplicationBuilder app, RouteGroupBuilder parentGroup"
            : "this IEndpointRouteBuilder builder, IApplicationBuilder app";

        var method = fileScope.AddMethod(
            modifiers: "private static",
            returnType: groupDefinition.IsConditionallyMapped ? "RouteGroupBuilder?" : "RouteGroupBuilder",
            methodName: names.MethodName(groupDefinition),
            parameters: parameters
        );

        if (groupDefinition.IsConditionallyMapped)
        {
            method.AddLine($"if (!{groupDefinition.ClassType.FullName}.ShouldMap(app))");
            method.AddLine("{");
            method.AddLine("return null;", additionalIndentation: 1);
            method.AddLine("}");
            method.AddEmptyLine();
        }

        // Map to parent group or main builder
        var builderExpression = hasParent ? "parentGroup" : "builder";

        method.AddLine(
            $"var group = {builderExpression}.MapGroup(\"{CSharpLiteral.EscapeStringContent(groupDefinition.Prefix)}\");");

        if (groupDefinition.IsConfigurable)
        {
            method.AddLine($"{groupDefinition.ClassType.FullName}.ConfigureGroup(app, group);");
        }

        method.AddLine($"return group;");

        return fileScope;
    }

    private static CSharpFileScope AddMinimalEndpointMapMethod(
        this CSharpFileScope fileScope,
        EndpointDefinition endpoint,
        GroupHierarchy hierarchy,
        GeneratedNames names
    )
    {
        const string instanceParameterBaseName = "endpointInstance";

        var hasGroup = endpoint.MapMethodsAttribute.GroupTypeName != null
                       && hierarchy.TryGet(endpoint.MapMethodsAttribute.GroupTypeName, out _);
        // Determine parameters: if endpoint has a group, include it
        var methodParameters = hasGroup
            ? "this IEndpointRouteBuilder builder, IApplicationBuilder app, RouteGroupBuilder group"
            : "this IEndpointRouteBuilder builder, IApplicationBuilder app";

        var method = fileScope.AddMethod(
            modifiers: "private static",
            returnType: endpoint.IsConditionallyMapped ? "IEndpointRouteBuilder?" : "IEndpointRouteBuilder",
            methodName: names.MethodName(endpoint),
            parameters: methodParameters
        );

        var usings = fileScope.GetAvailableUsings();
        var classTypeName = endpoint.ClassType.ToDisplayString(usings);
        var serviceName = endpoint.MapMethodsAttribute.ServiceName ?? classTypeName;
        var parameterList = BuildParameterList(endpoint, usings);
        var methodArguments = endpoint.EntryPoint.Parameters.Count > 0
            ? string.Join(", ", endpoint.EntryPoint.Parameters.Select(p => p.Key.EscapeIdentifier()))
            : "";

        var instanceParameterName = "endpointInstance";
        var index = 0;

        while (endpoint.EntryPoint.Parameters.ContainsKey(instanceParameterName))
        {
            instanceParameterName = GetUniqueIndexedName(instanceParameterBaseName, ++index);
        }

        parameterList.Insert(0, $"[FromServices]{serviceName} {instanceParameterName}");

        var returnTypeName = endpoint.EntryPoint.ReturnType.ToDisplayString(usings);

        if (endpoint.IsConditionallyMapped)
        {
            method.AddLine($"if (!{classTypeName}.ShouldMap(app))");
            method.AddLine("{");
            method.AddLine("return null;", additionalIndentation: 1);
            method.AddLine("}");
            method.AddEmptyLine();
        }

        method.AddLine(
            $"static {returnTypeName} Handler({string.Join(", ", parameterList)})"
        );
        method.AddLine("{");
        method.AddLine($"return {instanceParameterName}.{endpoint.EntryPoint.Name}({methodArguments});",
            additionalIndentation: 1);
        method.AddLine("}");

        method.AddEmptyLine();

        var pattern = endpoint.MapMethodsAttribute.Pattern;

        // Determine the builder to use (group parameter or main builder)
        var builderExpression = hasGroup ? "group" : "builder";

        // The dedicated MapGet/MapPost/MapPut/MapDelete/MapPatch builder methods take only a
        // pattern and handler. Everything else (explicit [MapMethods], plus verbs with no
        // dedicated method such as HEAD) goes through MapMethods(pattern, [verbs], Handler).
        var escapedPattern = CSharpLiteral.EscapeStringContent(pattern);
        if (endpoint.MapMethodsAttribute.EndpointBuilderMethodName == "MapMethods")
        {
            var methods = string.Join(", ",
                endpoint.MapMethodsAttribute.Methods.Select(m =>
                    $"\"{CSharpLiteral.EscapeStringContent(m.ToUpperInvariant())}\""));
            // Emit an explicit string[] rather than a C# 12 collection expression so the generated
            // code compiles for consumers pinned below LangVersion 12.
            method.AddLine(
                $"var endpoint = {builderExpression}.MapMethods(\"{escapedPattern}\", new string[] {{ {methods} }}, Handler);");
        }
        else
        {
            method.AddLine(
                $"var endpoint = {builderExpression}.{endpoint.MapMethodsAttribute.EndpointBuilderMethodName}(\"{escapedPattern}\", Handler);");
        }

        if (endpoint.IsConfigurable)
        {
            method.AddLine($"{classTypeName}.Configure(app, endpoint);");
        }

        method.AddLine("return builder;");

        return fileScope;
    }

    private static string GetUniqueIndexedName(string name, int index)
    {
        return index <= 0 ? name : $"{name}{index}";
    }

    private static void AddMinimalEndpointsMapAllMethods(this CSharpFileScope fileScope,
        List<EndpointDefinition> endpoints,
        GroupHierarchy hierarchy,
        GeneratedNames names
    )
    {
        var method = fileScope.AddMethod(
            modifiers: "public static",
            returnType: "IApplicationBuilder",
            methodName: "UseMinimalEndpoints",
            parameters: "this IApplicationBuilder app"
        );

        method.AddLine(
            "var builder = app as IEndpointRouteBuilder ?? throw new ArgumentException(\"IApplicationBuilder is not an IEndpointRouteBuilder\");");

        if (hierarchy.Count > 0)
        {
            method.AddEmptyLine();
            method.AddLine("// Create and configure groups in hierarchy order");

            // Sort groups by hierarchy: parents before children
            var sortedGroups = hierarchy.Groups.OrderBy(hierarchy.DepthOf);

            foreach (var group in sortedGroups)
            {
                var variableName = names.VariableName(group);
                var methodName = names.MethodName(group);
                var parent = hierarchy.Parent(group);
                if (parent is not null)
                {
                    var parentVariableName = names.VariableName(parent);
                    method.AddLine(hierarchy.HierarchyConditionallyMappedOf(group)
                        ? $"var {variableName} = {parentVariableName} is null ? null : builder.{methodName}(app, {parentVariableName});"
                        : $"var {variableName} = builder.{methodName}(app, {parentVariableName});");
                }
                else
                {
                    method.AddLine($"var {variableName} = builder.{methodName}(app);");
                }
            }

            method.AddEmptyLine();
        }

        method.AddLine("// Map endpoints");

        var (endpointsWithoutGroups, endpointsWithGroups) = GroupEndpointsByGroup(endpoints);

        foreach (var endpoint in endpointsWithoutGroups)
        {
            method.AddLine($"builder.{names.MethodName(endpoint)}(app);");
        }

        foreach (var pair in endpointsWithGroups)
        {
            if (hierarchy.TryGet(pair.Key, out var group))
            {
                var variableName = names.VariableName(group);
                var indentationLevel = 0;
                if (hierarchy.HierarchyConditionallyMappedOf(group))
                {
                    method.AddLine($"if ({variableName} is not null)");
                    method.AddLine("{");
                    indentationLevel = 1;
                }

                foreach (var endpoint in pair.Value)
                {
                    var mapEndpointLine = $"builder.{names.MethodName(endpoint)}(app, {variableName});";
                    method.AddLine(mapEndpointLine, indentationLevel);
                }

                if (hierarchy.HierarchyConditionallyMappedOf(group))
                {
                    method.AddLine("}");
                }
            }
            else
            {
                foreach (var endpoint in pair.Value)
                {
                    method.AddLine($"builder.{names.MethodName(endpoint)}(app);");
                }
            }
        }

        method.AddLine("return app;");
    }

    private static (List<EndpointDefinition> endpointsWithoutGroups, Dictionary<string, List<EndpointDefinition>> endpointsWithGroups) GroupEndpointsByGroup(List<EndpointDefinition> endpoints)
    {
        var endpointsWithoutGroups = new List<EndpointDefinition>();
        var endpointsWithGroups = new Dictionary<string, List<EndpointDefinition>>();

        foreach (var endpoint in endpoints)
        {
            if (endpoint.MapMethodsAttribute.GroupTypeName == null)
            {
                endpointsWithoutGroups.Add(endpoint);
            }
            else
            {
                if (!endpointsWithGroups.TryGetValue(endpoint.MapMethodsAttribute.GroupTypeName, out var list))
                {
                    endpointsWithGroups[endpoint.MapMethodsAttribute.GroupTypeName] = list = [];
                }

                list.Add(endpoint);
            }
        }

        return (endpointsWithoutGroups, endpointsWithGroups);
    }

    private static List<string> BuildParameterList(EndpointDefinition endpoint, HashSet<string> usings)
    {
        return endpoint.EntryPoint.Parameters.Select(p =>
            {
                var attributesString = BuildParameterAttributes(p.Value, usings);
                var typeName = p.Value.Type.ToDisplayString(usings);
                var nullableSign = p.Value.Nullable && !typeName.EndsWith("?") ? "?" : "";
                // Reproduce the optional default so ASP.NET Core keeps treating the parameter as
                // optional; without it a missing query value yields HTTP 400 instead of the default.
                var defaultValue = p.Value.DefaultValue != null ? $" = {p.Value.DefaultValue}" : "";
                return $"{attributesString}{typeName}{nullableSign} {p.Value.Name.EscapeIdentifier()}{defaultValue}";
            })
            .ToList();
    }

    public static string BuildParameterAttributes(ParameterInfo parameter, HashSet<string> usings)
    {
        if (parameter.Attributes.Count == 0)
        {
            return string.Empty;
        }

        var sb = new StringBuilder();
        foreach (var attr in parameter.Attributes)
        {
            var attrString = attr.ToDisplayString(usings);
            if (!string.IsNullOrEmpty(attrString))
            {
                if (sb.Length > 0)
                {
                    sb.Append(' ');
                }

                sb.Append(attrString);
            }
        }

        return sb.Length > 0 ? sb.Append(' ').ToString() : string.Empty;
    }

    private static string GetLifetimeMethodName(ServiceLifetime lifetime) => lifetime switch
    {
        ServiceLifetime.Singleton => "AddSingleton",
        ServiceLifetime.Transient => "AddTransient",
        _ => "AddScoped"
    };
}
